Repository zhmcclient/zhmccli, pull requests merged in 2023-03, with the labels that each got.

#347 Upgrade zhmcclient to 1.6.0 release
  docs/changes.rst
  minimum-constraints.txt
  requirements.txt
Labels: review needed

#366 Fixes #362: adapter mapping file schema
  docs/changes.rst
  zhmccli/_cmd_cpc.py
Labels: review needed

#375 Fixed zhmcclient dependency issue in local 'make install'
  minimum-constraints.txt
  requirements.txt
  setup.py
Labels: rollback done

#376 Increased zhmcclient to 1.7.0
  docs/changes.rst
  minimum-constraints.txt
  requirements.txt
Labels: rollback done

#382 Fixes #369: add support for --include-unused-adapters
  docs/changes.rst
  zhmccli/_cmd_cpc.py
Labels: area: code, type: feature, review needed

#383 Release 1.6.0
  docs/changes.rst
  zhmccli/_version.py
Labels: review needed

#374 Support for unmanaged CPCs
  docs/changes.rst
  zhmccli/__init__.py
  zhmccli/_cmd_unmanaged_cpc.py
Labels: review needed
